version: "3"
services:
    nginx:
        build:
            context: docker/nginx
            dockerfile: Dockerfile
        ports:
            - 8080:80
        volumes:
            - ./src:/var/www
            - nginx:/var/log/nginx
        depends_on:
            - php
    php:
        build:
            context: docker/php
            dockerfile: php-fpm.docker
        volumes:
            - ./src:/var/www
        env_file:
            - ./docker/php/.env
        depends_on:
            - db
    php-cli:
        build:
            context: docker/php
            dockerfile: php-cli.docker
        volumes:
            - ./src:/var/www
        depends_on:
            - db
    db:
        image: mysql:5.7
        ports:
            - 33061:3306
        env_file:
            - ./docker/db/.env
        volumes:
            - db:/var/lib/mysql

volumes:
    nginx:
    db:
